// Generated by CoffeeScript 1.6.3
var through, upper;

through = require('through');

upper = through(function(buf) {
  return this.queue(buf.toUpperCase());
});

process.stdin.setEncoding('utf8');

process.stdin.pipe(upper).pipe(process.stdout);
